In [1]:
import numpy as np
import sys
import os
os.chdir("..")

In [2]:
sys.path.insert(0, "/datos/practica-1-segunda-parte-caroacostatovany")

In [3]:
from src.mex.simplex.simplex_networks import *
from src.mex.simplex.problem_definition import *

# Pruebas

### Ejemplo modelo prototipo

In [4]:
m = create_matrix(2, 4)
constrain(m,'2,5,G,30')
constrain(m,'-3,5,G,5')
constrain(m,'8,3,L,85')
constrain(m,'-9,7,L,42')
obj(m,'2,7,0')
print(m)
print(minz(m))

[[ -2.  -5.   1.   0.   0.   0.   0. -30.]
 [  3.  -5.   0.   1.   0.   0.   0.  -5.]
 [  8.   3.   0.   0.   1.   0.   0.  85.]
 [ -9.   7.   0.   0.   0.   1.   0.  42.]
 [ -2.  -7.   0.   0.   0.   0.   1.   0.]]
{'x1': 5.0, 'x2': 4.0}


## Ejemplo prototipo redes

In [5]:
n_variables = 7
n_restricciones = 5

In [6]:
prototipo_red = create_matrix(n_variables, n_restricciones)

### Ejemplo Lema de Farkas con igualdades

In [7]:
prototipo_red = create_matrix(n_variables, n_restricciones)
constrain(prototipo_red,'1,1,1,0,0,0,0,E,50')
constrain(prototipo_red,'-1,0,0,1,0,0,0,E,40')
constrain(prototipo_red,'0,-1,0,-1,1,0,0,E,0')
constrain(prototipo_red,'0,0,-1,0,0,1,-1,E,-30')
constrain(prototipo_red,'0,0,0,0,-1,-1,1,E,-60')

In [8]:
prototipo_red

array([[  1.,   1.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  50.],
       [ -1.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  40.],
       [  0.,  -1.,   0.,  -1.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.],
       [  0.,   0.,  -1.,   0.,   0.,   1.,  -1.,   0.,   0.,   0.,   0.,
          0.,   0., -30.],
       [  0.,   0.,   0.,   0.,  -1.,  -1.,   1.,   0.,   0.,   0.,   0.,
          0.,   0., -60.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.]])

In [9]:
# Agregamos la función objetivo
obj(prototipo_red, '2,4,9,3,1,3,2,0')
minz(prototipo_red)

{'x1': 50.0,
 'x2': 50.0,
 'x3': 0,
 'min': 470.0,
 'x4': 40.0,
 'x5': 90.0,
 'x6': 0,
 'x7': 30.0}