In [1]:
import numpy as np
from simplex_networks import *

In [2]:
n_variables = 2
n_restricciones = 5

In [3]:
create_matrix(n_variables,n_restricciones)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
matrix = np.array([[ 1, 0, 1, 0, 0, 0,  4],
                   [ 0, 2, 0, 1, 0, 0, 12],
                   [ 3, 2, 0, 0, 1, 0, -18],
                   [-3, 5, 0, 0, 0, 1,  0]])

In [5]:
pivots_col(matrix)

True

In [6]:
pivots_row(matrix)

True

In [7]:
find_negative_col(matrix)

2

In [8]:
find_negative_row(matrix)

0

In [9]:
find_pivot_col(matrix)

[0, 2]

In [10]:
find_pivot_row(matrix)

[0, 0]

In [11]:
if pivots_col(matrix) == True:
    table = pivot(find_pivot_col(matrix)[0],find_pivot_col(matrix)[1],matrix)
    print(table)  
else:
    print("no")

[[  1.   0.   1.   0.   0.   0.   4.]
 [  0.   2.   0.   1.   0.   0.  12.]
 [  3.   2.   0.   0.   1.   0. -18.]
 [ -3.   5.   0.   0.   0.   1.   0.]]


In [27]:
if pivots_row(matrix) == True:
    table = pivot(find_pivot_row(matrix)[0],find_pivot_row(matrix)[1],matrix)
    print(table)  
else:
    print("no")

[[  1.   0.   1.   0.   0.   0.   4.]
 [  0.   2.   0.   1.   0.   0.  12.]
 [  0.   2.  -3.   0.   1.   0. -30.]
 [  0.   5.   3.   0.   0.   1.  12.]]
